---
- hosts: 10.1.0.5
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name:  i want to create folder
    file:
      path: /home/maha/myfolder
      state: directory
  - name: i want to copy a file
    copy:
       src: mystaticfile
       dest: /home/maha/

  - name: i want install apache2 
    apt:
      name: apache2
      state: present

  - name: i want to copy index file into node side
    template:
       src:
       dest: /var/www/html/index.html
 