---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: install webserver on ansible nodes
    apt:
      name: apache2
      state: present

  - name: start webserver
    service:
      name: apache2
      state: started  
    