---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: install webserver on ansible nodes ( apt can execute on ubuntu)
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver
    service:
      name: apache2
      state: started  
    when: ansible_os_family=="Debian"